spring.application.name=spring
server.port=8088
spring.main.allow-circular-references=true

api.route.path=/api/

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect


spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=

spring.mail.host=smtp.qq.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=YourSecretKeyForJwtTokenGeneration1234567890
jwt.expiration=86400000

